name: learnhub
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  flutter_bloc: ^8.1.6
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0

  fluttertoast: ^8.2.8
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
  dio: ^5.7.0
  connectivity_plus: ^6.0.5
  internet_connection_checker_plus: ^2.5.1
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  dartz: ^0.10.1
  percent_indicator: ^4.2.3

  carousel_slider: ^5.0.0
  gradient_slider: ^1.0.2

  smooth_page_indicator: ^1.2.0+3
  flutter_facebook_auth: ^7.1.1
  google_sign_in: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/fonts/


#  fonts:
#    - family: poppins
#      fonts:
#        - asset: assets/fonts/poppins_regular.ttf
#        - asset: assets/fonts/poppins_medium.ttf
#          weight: 500
#        - asset: assets/fonts/poppins_bold.ttf
#          weight: 700

